/**
 * Auto-generated from OBS configuration
 * Generated by @sceneify/obs-to-code
 */

import { FilterType, Input, Scene } from "@sceneify/core-rewrite";
import {
  BrowserSource,
  ColorSource,
  CoreAudioInputCapture,
  FreetypeTextSource,
  GainFilter,
  MacOSScreenCapture,
  NoiseGateFilter,
  NoiseSuppressFilter,
  VideoCaptureSource,
} from "@sceneify/sources";

// ─── Inline Type Definitions ────────────────────────────────────────────────

class ShaderFilterFilter extends FilterType("shader_filter")<{
  corner_radius: number;
  from_file: boolean;
  override_entire_effect: boolean;
  shader_file_name: string;
}>() {}
class ObsCompositeBlurFilter extends FilterType("obs_composite_blur")<{
  blur_algorithm: number;
  blur_type: number;
  kawase_passes: number;
  pixelate_origin_x: number;
  pixelate_origin_y: number;
  radius: number;
}>() {}

// ─── Input Declarations ─────────────────────────────────────────────────────

const webcam = Input.declare(VideoCaptureSource, {
  name: "Webcam",
  settings: {
    device: "0x2120000046d085c",
    device_name: "C922 Pro Stream Webcam",
    frame_rate: {
      denominator: 1000000,
      numerator: 60000240,
    },
    preset: "AVCaptureSessionPreset1920x1080",
    resolution: '{"width":1280,"height":720}',
    use_preset: true,
  },
  filters: {
    zoom: {
      type: ShaderFilterFilter,
      name: "zoom",
      settings: {
        center_y_percent: 44,
        from_file: true,
        override_entire_effect: false,
        power: 1,
        shader_file_name:
          "/Users/brendonovich/Library/Application Support/obs-studio/plugins/obs-shaderfilter.plugin/Contents/Resources/examples/zoom.shader",
      },
    },
  },
});

const display = Input.declare(MacOSScreenCapture, {
  name: "Display",
  settings: {
    application: "com.brave.Browser",
    display_uuid: "37D8832A-2D66-02CA-B9F7-8F30A301B230",
    hide_obs: true,
    type: 0,
  },
  filters: {
    blur: {
      type: ObsCompositeBlurFilter,
      name: "Blur",
      settings: {
        blur_algorithm: 3,
        blur_type: 1,
        kawase_passes: 48,
        pixelate_origin_x: 1728,
        pixelate_origin_y: 1117,
        radius: 55.4,
      },
      enabled: false,
    },
    userDefinedShader: {
      type: ShaderFilterFilter,
      name: "User-defined shader",
      settings: {
        corner_radius: 20,
        from_file: true,
        override_entire_effect: false,
        shader_file_name:
          "/Users/brendonovich/Library/Application Support/obs-studio/plugins/obs-shaderfilter.plugin/Contents/Resources/examples/rounded_rect.shader",
      },
    },
  },
});

const guest = Input.declare(BrowserSource, {
  name: "Guest",
  settings: {
    height: 1080,
    url: "https://ping.gg/call/brendonovich/embed?view=cl8287d6q12920gmk8bbjyff5",
    width: 1920,
  },
});

const chat = Input.declare(BrowserSource, {
  name: "Chat",
  settings: {
    css: "",
    height: 1480,
    url: "https://streamlabs.com/widgets/chat-box/v1/70317455E999E73D5134",
    width: 770,
  },
  filters: {
    userDefinedShader: {
      type: ShaderFilterFilter,
      name: "User-defined shader",
      settings: {
        corner_radius: 15,
        from_file: true,
        override_entire_effect: false,
        shader_file_name:
          "/Users/brendonovich/Library/Application Support/obs-studio/plugins/obs-shaderfilter.plugin/Contents/Resources/examples/rounded_rect.shader",
      },
    },
  },
});

const discordServer = Input.declare(BrowserSource, {
  name: "Discord Server",
  settings: {
    css: "body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }",
    height: 64,
    url: "https://streamkit.discord.com/overlay/status/1391832426048651334?icon=true&online=true&logo=white&text_color=%23ffffff&text_size=14&text_outline_color=%23000000&text_outline_size=0&text_shadow_color=%23000000&text_shadow_size=0&bg_color=%231e2124&bg_opacity=0.95&bg_shadow_color=%23000000&bg_shadow_size=0&invite_code=opencode&limit_speaking=false&small_avatars=false&hide_names=false&fade_chat=0&streamer_avatar_first=false",
    width: 312,
  },
});

const micAudio = Input.declare(CoreAudioInputCapture, {
  name: "Mic Audio",
  settings: {
    device_id: "40-B3-FA-17-E5-97:input",
    enable_downmix: true,
    "output-dioEngine_Unknown_Manufacturer_C922_Pro_Stream_Webcam_79D9EE4F_3-1": 1,
    "output-dioEngine_Unknown_Manufacturer_C922_Pro_Stream_Webcam_79D9EE4F_3-2": 2,
  },
  filters: {
    gain: {
      type: GainFilter,
      name: "Gain",
      settings: {
        db: 3.7,
      },
      enabled: false,
    },
    noiseSuppression: {
      type: NoiseSuppressFilter,
      name: "Noise Suppression",
      settings: {
        method: "rnnoise",
      },
    },
    noiseGate: {
      type: NoiseGateFilter,
      name: "Noise Gate",
      settings: {
        attack_time: 25,
        close_threshold: -50,
        open_threshold: -45,
      },
      enabled: false,
    },
  },
});

const browser = Input.declare(BrowserSource, {
  name: "Browser",
  settings: {
    height: 1080,
    shutdown: false,
    url: "https://loading.io/background/m-network/",
    width: 1920,
  },
});

const streamkitVoice = Input.declare(BrowserSource, {
  name: "Streamkit Voice",
  settings: {
    css: "body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }\nul { padding: 0; margin: 0; display: flex; flex-direction: row; gap: 16px; }\nli { display: flex; flex-direction: row; }",
    height: 60,
    url: "https://streamkit.discord.com/overlay/voice/1101415635449286729/1101415636221055019?icon=true&online=true&logo=white&text_color=%23ffffff&text_size=14&text_outline_color=%23000000&text_outline_size=0&text_shadow_color=%23000000&text_shadow_size=0&bg_color=%231e2124&bg_opacity=0.95&bg_shadow_color=%23000000&bg_shadow_size=0&invite_code=FEyYaC8v53&limit_speaking=false&small_avatars=false&hide_names=true&fade_chat=0&streamer_avatar_first=true",
    width: 600,
  },
});

const brbText = Input.declare(FreetypeTextSource, {
  name: "BRB Text",
  settings: {
    color2: 4294967295,
    drop_shadow: false,
    font: {
      face: "Helvetica",
      flags: 0,
      size: 256,
      style: "Regular",
    },
    outline: true,
    text: "brb",
  },
});

const background = Input.declare(ColorSource, {
  name: "Background",
  settings: {
    color: 4279900718,
    height: 1080,
    width: 1920,
  },
});

// ─── Scene Declarations ─────────────────────────────────────────────────────

const brbBase = Scene.declare({
  name: "BRB Base",
  items: {},
});

const brb = Scene.declare({
  name: "BRB",
  items: {
    brbText: {
      source: brbText,
      transform: {
        positionX: 775.5,
        positionY: 418,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 1,
    },
  },
});

const mainScene = Scene.declare({
  name: "Main Scene",
  items: {
    background: {
      source: background,
      transform: {
        positionX: 0,
        positionY: 0,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 0,
    },
  },
});

const base = Scene.declare({
  name: "Base",
  items: {
    browser: {
      source: browser,
      transform: {
        positionX: 0,
        positionY: 0,
        scaleX: 1.0505207777023315,
        scaleY: 1.0509259700775146,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 0,
    },
    display: {
      source: display,
      transform: {
        positionX: 10,
        positionY: 10,
        scaleX: 0.44155094027519226,
        scaleY: 0.44136080145835876,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 1,
    },
    discordServer: {
      source: discordServer,
      transform: {
        positionX: 322,
        positionY: 1006,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 3,
    },
    micAudio: {
      source: micAudio,
      transform: {
        positionX: 0,
        positionY: 0,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 4,
    },
    guest: {
      source: guest,
      transform: {
        positionX: -6,
        positionY: -95,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 5,
    },
    chat: {
      source: chat,
      transform: {
        positionX: 1910,
        positionY: 704,
        scaleX: 0.4688311815261841,
        scaleY: 0.46891891956329346,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 6,
    },
    streamkitVoice: {
      source: streamkitVoice,
      transform: {
        positionX: 322,
        positionY: 1008,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        cropTop: 0,
        cropBottom: 0,
        cropLeft: 0,
        cropRight: 0,
      },
      index: 7,
    },
  },
});

// ─── Exports ────────────────────────────────────────────────────────────────

export {
  webcam,
  display,
  guest,
  chat,
  discordServer,
  micAudio,
  browser,
  streamkitVoice,
  brbText,
  background,
  brbBase,
  brb,
  mainScene,
  base,
};
